name: Deploy para EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docket login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-simple-api-ec2 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-simple-api-ec2:latest

  deploy:
    runs-on: [aws-ec2]
    needs: build
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/node-simple-api-ec2:latest

      - name: Run Docker container
        run: docker run -d -p 3000:3000 -name app-container ${{ secrets.DOCKER_USERNAME }}/node-simple-api-ec2:latest
