name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH
        run: |
          # Criar o diretório .ssh se não existir
          mkdir -p $HOME/.ssh
          
          # Configurar a chave SSH para autenticação
          echo "${{ secrets.EC2_SSH_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519  # Definir permissões corretas para a chave SSH
          
          # Adicionar o host da EC2 ao known_hosts para evitar erro de "host desconhecido"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Conectar na EC2 e atualizar o código
        run: |
          # Conectar à instância EC2 e executar os comandos de deploy
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/app
            git pull origin main
            npm install --production  # Instalar dependências para produção
            sudo systemctl restart myapp.service  # Reiniciar o serviço
          EOF
